apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-credentials
spec:
  target:
    name: api-credentials
  data:
    - secretKey: API_PASSWORD
      remoteRef:
        key: secret/data/demo
        property: password
